services:
    api_gw:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db_api_gw:5432/journey_radar_api_gw
        depends_on:
            db_api_gw:
                condition: service_healthy
    
    db_api_gw:
        container_name: db_api_gw
        image: postgres:17
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: journey_radar_api_gw
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:  
    pgdata: {}