"""initial

Revision ID: 263cce2c40bf
Revises: 
Create Date: 2025-10-04 18:43:48.967977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263cce2c40bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('T', 'A', 'M', name='vehicletype'), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vehicle_type')
    )
    op.create_table('stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('T', 'A', 'M', name='vehicletype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vehicle_type')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('T', 'A', 'M', name='vehicletype'), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_vehicle_type', sa.Enum('T', 'A', 'M', name='vehicletype'), nullable=False),
    sa.Column('headsign', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_id', 'route_vehicle_type'], ['routes.id', 'routes.vehicle_type'], ),
    sa.PrimaryKeyConstraint('id', 'vehicle_type')
    )
    op.create_table('stop_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('trip_vehicle_type', sa.Enum('T', 'A', 'M', name='vehicletype'), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_vehicle_type', sa.Enum('T', 'A', 'M', name='vehicletype'), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id', 'stop_vehicle_type'], ['stops.id', 'stops.vehicle_type'], ),
    sa.ForeignKeyConstraint(['trip_id', 'trip_vehicle_type'], ['trips.id', 'trips.vehicle_type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stop_times')
    op.drop_table('trips')
    op.drop_table('stops')
    op.drop_table('routes')
    # ### end Alembic commands ###
